<?php

/*
 +-----------------------------------------------------------------------+
 | localization/es_ES/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Thomas                                                        |
 +-----------------------------------------------------------------------+
*/

$labels = array();
$labels['changepasswd'] = 'Cambiar contraseña';
$labels['curpasswd'] = 'Contraseña actual:';
$labels['newpasswd'] = 'Contraseña nueva:';
$labels['confpasswd'] = 'Confirmar contraseña:';
$labels['nopassword'] = 'Por favor introduzca una contraseña nueva.';
$labels['nocurpassword'] = 'Por favor introduzca la contraseña actual.';
$labels['passwordincorrect'] = 'La contraseña actual es incorrecta.';
$labels['passwordinconsistency'] = 'Las contraseñas no coinciden. Por favor, inténtelo de nuevo.';
$labels['crypterror'] = 'No se pudo guardar la contraseña nueva. Falta la función de cifrado.';
$labels['connecterror'] = 'No se pudo guardar la contraseña nueva. Error de conexión';
$labels['internalerror'] = 'No se pudo guardar la contraseña nueva.';
$labels['passwordshort'] = 'La nueva contraseña debe tener $length caracteres o más.';
$labels['passwordweak'] = 'La nueva contraseña debe incluir al menos un número y un signo de puntuación.';
$labels['passwordforbidden'] = 'La contraseña introducida contiene caracteres no permitidos.';
//Valarauco
$labels['restrictions'] = 'Para cambiar la contraseña debe cumplir lo siguiente:';
$labels['passwordconfirm_current'] = 'Debe introducir la contraseña actual.';
$labels['passwordexample'] = 'Ejemplo de contraseña válida: ';
$labels['passwordexampleerror'] = 'Por favor no utilice el ejemplo como contraseña.';
$labels['passwordsaved'] = 'Contraseña guardada.';

